
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 21 21:53:44 MDT 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 39;
  public static final int GE = 14;
  public static final int SLASH = 22;
  public static final int BVAL = 53;
  public static final int SLPAR = 20;
  public static final int CASE = 34;
  public static final int INT = 37;
  public static final int FLOOR = 45;
  public static final int DATA = 42;
  public static final int NOT = 9;
  public static final int AND = 7;
  public static final int LT = 11;
  public static final int RPAR = 17;
  public static final int FUN = 47;
  public static final int OR = 8;
  public static final int BOOL = 38;
  public static final int COMMA = 25;
  public static final int DIV = 5;
  public static final int BEGIN = 32;
  public static final int ASSIGN = 15;
  public static final int IF = 26;
  public static final int ID = 50;
  public static final int LE = 13;
  public static final int OF = 35;
  public static final int EOF = 0;
  public static final int RETURN = 48;
  public static final int SEMICLON = 24;
  public static final int EQUAL = 10;
  public static final int SIZE = 43;
  public static final int CLPAR = 18;
  public static final int CVAL = 54;
  public static final int error = 1;
  public static final int MUL = 4;
  public static final int ADD = 2;
  public static final int SRPAR = 21;
  public static final int REAL = 40;
  public static final int ARROW = 6;
  public static final int RVAL = 51;
  public static final int COLON = 23;
  public static final int CID = 49;
  public static final int ELSE = 31;
  public static final int READ = 30;
  public static final int WHILE = 28;
  public static final int FLOAT = 44;
  public static final int THEN = 27;
  public static final int END = 33;
  public static final int LPAR = 16;
  public static final int CEIL = 46;
  public static final int GT = 12;
  public static final int SUB = 3;
  public static final int VAR = 41;
  public static final int PRINT = 36;
  public static final int DO = 29;
  public static final int CRPAR = 19;
  public static final int IVAL = 52;
}

